Seats page
rickertmar/KinoticketFrontend pull request #48
Opened 2023-09-08 23:58 UTC by uiyoungkim

- erst mal nicht dynamisch d.h. unabhängig davon welche Zeit ausgewählt wurde, wird immer gleiche sitzplätze angezeigt -> testdaten in JSON 

-man kann sicherlich noch besser designen aber erst mal zum zeigen ist voll gut finde ich
-> ich habe nicht ganz verstanden mit sitzplätze API aber es lohnt sich nicht noch si viele mit ROW und nummer design zu beschäftigen wenn wir noch keine Abfrage machen oder?

2023-09-09 00:13 UTC, K-Lorenz requested changes
Sieht erstmal schon sehr wild aus. Aber müssen noch n paar changes gemacht werden wie die Seats reinkommen. Die haben eine yLoc xLoc, also wie ein Koordinatensystem. Und der chart soll sich dann dementsprechend aufbauen. Wegen der Json datei. Muss keine echte Datei sein. Reicht wenn du: 
`const jsondate = [
{
id: "1",
usw: "blabla",
},
{
id: "2",
usw: "nafs+dajf",
},
...
...
..
]
`

2023-09-09 00:15 UTC, K-Lorenz commented
> 

Wenn du willst können wir mal zusammen drüber schauen. Aber wie gesagt vom Konzept schon sehr wild. Und mag das Design sehr. Die seats müssen eigtl nur bisschen anders generiert werden.

2023-09-09 06:42 UTC, rickertmar commented
Die Json Datei, die das Backend für die Seats von einer CinemaHall zurückgibt, sieht so aus:

```
[
  {
    "id": 1,
    "seatRow": 1,
    "number": 101,
    "xloc": 10,
    "yloc": 20,
    "blocked": false
  },
  {
    "id": 2,
    "seatRow": 1,
    "number": 102,
    "xloc": 15,
    "yloc": 20,
    "blocked": true
  },
  {
    "id": 3,
    "seatRow": 2,
    "number": 201,
    "xloc": 10,
    "yloc": 25,
    "blocked": false
  }
]
```

id : Long
seatRow : int
number : int
xloc : int
yloc : int
blocked : boolean

Wir könnten die id theoretisch noch rausnehmen, weil die autogenerated wird, aber das ist denke ich nur für Post Requests relevant.

2023-09-09 10:48 UTC, uiyoungkim commented
@K-Lorenz wegen details design können wir noch gerne schauen.
-> Nach allign mit @rickertmar  json- datei korrekt formating 
-> in backend wird auch seatRow den typ char bekommen statt int.
-> x und y loc spielt erst mal nicht so große Rolle. Soll aber später zu sitzplätze ordnung beitragen. In UI wird Row & number angezeigt z.B. A1

2023-09-10 13:51 UTC, zxTyphoon approved these changes

2023-09-10 13:52 UTC, zxTyphoon approved these changes

2023-09-10 13:57 UTC, K-Lorenz commented
Also ich finde das sieht eif noch nicht nach Kino aus:
![image](https://github.com/rickertmar/KinoticketFrontend/assets/86967062/f2729caf-ec65-4a7c-b3ec-a09f01c1e118)
Hier sieht man eigtl recht gut, wie das aussehen sollte. Du hast deine Reihen und plätze und das ganze ist anhand einer Art Koordinaten system angeordnet. Das was du programmiert hast finde ich sieht aus wie Flugzeugplatz buchen

2023-09-10 14:53 UTC, uiyoungkim commented
ja das stimmt also das ist denke ich machbar aber da wir keine API Abfrage machen wie stellst du dir das vor wenn ich so mit json testdaten so viele sitze mache wird das über 10,000 zeilen sein

2023-09-10 15:06 UTC, K-Lorenz commented
> ja das stimmt also das ist denke ich machbar aber da wir keine API Abfrage machen wie stellst du dir das vor wenn ich so mit json testdaten so viele sitze mache wird das über 10,000 zeilen sein

Ich schreib dir kurz eine Funktion die dir ein Kino generiert. 10 min

2023-09-10 15:11 UTC, K-Lorenz commented
```
function generateJsonData() {
  const jsonData = [];
  let id = 1;

  for (let seatRow = 1; seatRow <= 15; seatRow++) {
    for (let number = 1; number <= 35; number++) {
      const xloc = seatRow +2;
      const yloc = number + 1;
      const blocked = Math.random() < 0.1;

      const seatData = {
        id: id++,
        seatRow,
        number,
        xloc,
        yloc,
        blocked,
      };

      jsonData.push(seatData);
    }
  }

  return jsonData;
}
```

2023-09-11 18:01 UTC, uiyoungkim commented
Jetzt:
Walkway (Platzhalter-gehweg):

-  Zwischen Screen& Erste Row, 
- Zwischen Seat 10 & 11
- Zwischen Row 'J' & 'K'
+Responsive Design

2023-09-11 20:52 UTC, K-Lorenz approved these changes

2023-09-11 20:52 UTC, merged